-- User-generated content: ascent logs and comments.
--
-- Conventions for every user-created table (here and in V7):
--  * id is generated by the CLIENT (UUID). Android creates the record offline with
--    status "pending" and retries the upload; the same id makes the retry idempotent.
--  * Rows are never hard-deleted: deleted_at is a tombstone that offline clients sync.
--  * visibility = 'hidden' is a moderation decision, separate from author deletion.

CREATE TABLE ascents (
    id                  uuid PRIMARY KEY,
    route_id            uuid NOT NULL REFERENCES routes (id),
    user_id             uuid NOT NULL REFERENCES users (id),
    ascent_date         date NOT NULL,
    -- Old ascents are often known only to the month or year. Dates are normalized
    -- to the first day of the period so they sort correctly.
    date_precision      text NOT NULL DEFAULT 'day' CHECK (date_precision IN ('day', 'month', 'year')),
    outcome             text CHECK (outcome IN ('summit', 'retreat')),
    -- Moving time ("ходовое время").
    total_time_minutes  integer CHECK (total_time_minutes > 0),
    conditions          text CHECK (length(conditions) <= 5000),
    report              text CHECK (length(report) <= 20000),
    language            text CHECK (language ~ '^[a-z]{2}$'),
    is_private          boolean NOT NULL DEFAULT false,
    visibility          text NOT NULL DEFAULT 'visible' CHECK (visibility IN ('visible', 'hidden')),
    deleted_at          timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    -- Target of composite foreign keys: a photo/track of an ascent must be of the same route.
    UNIQUE (id, route_id),
    CHECK (date_precision = 'day' OR extract(day FROM ascent_date) = 1),
    CHECK (date_precision <> 'year' OR extract(month FROM ascent_date) = 1)
);

CREATE INDEX ascents_route_idx ON ascents (route_id, ascent_date DESC);
CREATE INDEX ascents_user_idx ON ascents (user_id, ascent_date DESC);
CREATE INDEX ascents_updated_idx ON ascents (updated_at);

CREATE TRIGGER ascents_updated_at BEFORE UPDATE ON ascents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Team members other than the author. A member may or may not be a registered user.
CREATE TABLE ascent_members (
    ascent_id  uuid NOT NULL REFERENCES ascents (id) ON DELETE CASCADE,
    position   smallint NOT NULL CHECK (position >= 0),
    user_id    uuid REFERENCES users (id),
    name       text CHECK (length(name) <= 200),
    is_leader  boolean NOT NULL DEFAULT false,
    PRIMARY KEY (ascent_id, position),
    CHECK (user_id IS NOT NULL OR COALESCE(btrim(name), '') <> '')
);

CREATE UNIQUE INDEX ascent_members_user_uq ON ascent_members (ascent_id, user_id) WHERE user_id IS NOT NULL;
CREATE INDEX ascent_members_user_idx ON ascent_members (user_id) WHERE user_id IS NOT NULL;

-- A comment belongs to a route or to an ascent; one level of replies via parent_id.
CREATE TABLE comments (
    id          uuid PRIMARY KEY,
    author_id   uuid NOT NULL REFERENCES users (id),
    route_id    uuid REFERENCES routes (id),
    ascent_id   uuid REFERENCES ascents (id),
    parent_id   uuid REFERENCES comments (id),
    body        text NOT NULL CHECK (btrim(body) <> '' AND length(body) <= 5000),
    language    text CHECK (language ~ '^[a-z]{2}$'),
    edited_at   timestamptz,
    visibility  text NOT NULL DEFAULT 'visible' CHECK (visibility IN ('visible', 'hidden')),
    deleted_at  timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(route_id, ascent_id) = 1),
    CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX comments_route_idx ON comments (route_id, created_at) WHERE route_id IS NOT NULL;
CREATE INDEX comments_ascent_idx ON comments (ascent_id, created_at) WHERE ascent_id IS NOT NULL;
CREATE INDEX comments_parent_idx ON comments (parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX comments_updated_idx ON comments (updated_at);

CREATE TRIGGER comments_updated_at BEFORE UPDATE ON comments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
